name: order-tracking-system

services:
  order-service-api:
    build:
      context: ./OrderService/.
      dockerfile: WebApi/Dockerfile
    image: order-service-api
    container_name: order-service-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
  
  order-service-outbox-worker:
    build:
      context: ./OrderService/.
      dockerfile: OutboxWorker/Dockerfile
    image: order-service-outbox-worker
    container_name: order-service-outbox-worker
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
    volumes:
      - ./OrderService/secrets/appsettings.Secrets.json:/app/Configurations/appsettings.Secrets.json:ro
    depends_on:
      - postgres
    networks:
      - backend
    
  courier-service-api:
    build:
      context: ./CourierService/.
      dockerfile: WebApi/Dockerfile
    image: courier-service-api
    container_name: courier-service-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=courier_service_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
    
  courier-service-kafka-consumer:
    build:
      context: ./CourierService/.
      dockerfile: KafkaConsumer/Dockerfile
    image: courier-service-kafka-consumer
    container_name: courier-service-kafka-consumer
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ./CourierService/secrets/appsettings.Secrets.json:/app/Configurations/appsettings.Secrets.json:ro
    depends_on:
      - courier-service-api
    networks:
      - backend
    
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - backend
  
  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - backend

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    depends_on:
      loki:
        condition: service_healthy
    networks:
      - backend
    
  
volumes:
  pgdata:
    
networks:
  backend: