name: order-tracking-system

services:
  order-service-api:
    build:
      context: ./OrderService/.
      dockerfile: WebApi/Dockerfile
    image: order-service-api
    container_name: order-service-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
  
  order-service-outbox-worker:
    build:
      context: ./OrderService/.
      dockerfile: OutboxWorker/Dockerfile
    image: order-service-outbox-worker
    container_name: order-service-outbox-worker
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
    volumes:
      - ./OrderService/secrets/appsettings.Secrets.json:/app/Configurations/appsettings.Secrets.json:ro
    depends_on:
      - postgres
    networks:
      - backend
    
  courier-service-api:
    build:
      context: ./CourierService/.
      dockerfile: WebApi/Dockerfile
    image: courier-service-api
    container_name: courier-service-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=courier_service_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - backend
    
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - backend
  
volumes:
  pgdata:
    
networks:
  backend: