name: order-tracking-system

services:
  api-gateway:
    build:
      context: ./ApiGateway/.
      dockerfile: ApiGateway/Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - order-service-api
      - courier-service-api
      - tracking-service-api
    networks:
      - backend

  order-service-api:
    build:
      context: ./OrderService/.
      dockerfile: WebApi/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: order-service-api
    container_name: order-service-api
    ports:
      - "8080:8080"
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - postgres
    networks:
      - backend
  
  order-service-outbox-worker:
    build:
      context: ./OrderService/.
      dockerfile: OutboxWorker/Dockerfile
    image: order-service-outbox-worker
    container_name: order-service-outbox-worker
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=order_service_db;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./OrderService/secrets/appsettings.Secrets.json:/app/Configurations/appsettings.Secrets.json:ro
    depends_on:
      - postgres
    networks:
      - backend
    
  courier-service-api:
    build:
      context: ./CourierService/.
      dockerfile: WebApi/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: courier-service-api
    container_name: courier-service-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Host=postgres-db;Port=5432;Database=courier_service_db;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - postgres
    networks:
      - backend
    
  courier-service-kafka-consumer:
    build:
      context: ./CourierService/.
      dockerfile: KafkaConsumer/Dockerfile
    image: courier-service-kafka-consumer
    container_name: courier-service-kafka-consumer
    environment:
      - DOTNET_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./CourierService/secrets/appsettings.Secrets.json:/app/Configurations/appsettings.Secrets.json:ro
    depends_on:
      - courier-service-api
    networks:
      - backend
  
  tracking-service-api:
    build:
      context: ./TrackingService/.
      dockerfile: WebApi/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    image: tracking-service-api
    container_name: tracking-service-api
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8082
      - ASPNETCORE_ENVIRONMENT=Development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    networks:
      - backend
    
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - backend
  
  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3100/ready
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - backend
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "16686:16686"
    networks:
      - backend

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started
      jaeger:
        condition: service_started
    networks:
      - backend
  
volumes:
  pgdata:
    
networks:
  backend: